import { BloodRequest, DonorProfile, DonationRecord, DashboardStats } from './types';

export const mockStats: DashboardStats = {
  totalUsers: 1480,
  totalDonors: 920,
  activeRequests: 34,
  criticalRequests: 8,
  fulfilledDonations: 852,
  livesSaved: 1140,
};

export const mockBloodRequests: BloodRequest[] = [
  {
    id: 'req-001',
    patient_name: 'Zubair Ahmed',
    blood_group: 'O-',
    units_required: 3,
    units_fulfilled: 1,
    hospital: 'Services Hospital',
    city: 'Lahore',
    urgency: 'CRITICAL',
    status: 'OPEN',
    contact_number: '+92 300 1234567',
    notes: 'Emergency bypass surgery required immediately. Rare O- negative needed.',
    requester_name: 'Dr. Tariq Mahmood',
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(), // 25 mins ago
    updated_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'req-002',
    patient_name: 'Fatima Noor',
    blood_group: 'A+',
    units_required: 2,
    units_fulfilled: 2,
    hospital: 'Shaukat Khanum Memorial Hospital',
    city: 'Lahore',
    urgency: 'HIGH',
    status: 'FULFILLED',
    contact_number: '+92 321 9876543',
    notes: 'Chemotherapy supportive transfusion.',
    requester_name: 'Rashid Noor (Brother)',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(), // 3 hours ago
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'req-003',
    patient_name: 'Bilal Khan',
    blood_group: 'B+',
    units_required: 4,
    units_fulfilled: 2,
    hospital: 'Aga Khan University Hospital',
    city: 'Karachi',
    urgency: 'CRITICAL',
    status: 'IN_PROGRESS',
    contact_number: '+92 333 5554321',
    notes: 'Trauma ICU patient from road accident.',
    requester_name: 'Usman Khan',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(), // 1.5 hours ago
    updated_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'req-004',
    patient_name: 'Ayesha Siddiqua',
    blood_group: 'AB-',
    units_required: 2,
    units_fulfilled: 0,
    hospital: 'Pakistan Institute of Medical Sciences (PIMS)',
    city: 'Islamabad',
    urgency: 'CRITICAL',
    status: 'OPEN',
    contact_number: '+92 345 7788990',
    notes: 'Thalassemia patient regular transfusion delayed.',
    requester_name: 'Imran Siddiqui',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'req-005',
    patient_name: 'Muhammad Umar',
    blood_group: 'A-',
    units_required: 1,
    units_fulfilled: 0,
    hospital: 'Mayo Hospital',
    city: 'Lahore',
    urgency: 'MEDIUM',
    status: 'OPEN',
    contact_number: '+92 312 4455667',
    notes: 'Scheduled orthopedic surgery tomorrow morning.',
    requester_name: 'Kashif Umar',
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
  {
    id: 'req-006',
    patient_name: 'Sana Malik',
    blood_group: 'B-',
    units_required: 2,
    units_fulfilled: 1,
    hospital: 'Jinnah Hospital',
    city: 'Lahore',
    urgency: 'HIGH',
    status: 'IN_PROGRESS',
    contact_number: '+92 301 8899001',
    notes: 'Post-delivery complication.',
    requester_name: 'Waqas Malik',
    created_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'req-007',
    patient_name: 'Hamza Ali',
    blood_group: 'O+',
    units_required: 2,
    units_fulfilled: 2,
    hospital: 'Nishtar Hospital',
    city: 'Multan',
    urgency: 'LOW',
    status: 'FULFILLED',
    contact_number: '+92 308 3322110',
    notes: 'Elective surgical procedure.',
    requester_name: 'Ali Raza',
    created_at: new Date(Date.now() - 1000 * 60 * 1440).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  }
];

export const mockDonors: DonorProfile[] = [
  {
    id: 'usr-101',
    name: 'Ali Hassan',
    email: 'ali.hassan@example.com',
    phone: '+92 300 1122334',
    blood_group: 'O-',
    city: 'Lahore',
    is_available: true,
    total_donations: 7,
    last_donation_date: '2026-06-15',
    created_at: '2025-01-10',
    verified: true,
  },
  {
    id: 'usr-102',
    name: 'Dr. Sarah Farooq',
    email: 'sarah.farooq@health.pk',
    phone: '+92 321 4455667',
    blood_group: 'A+',
    city: 'Lahore',
    is_available: true,
    total_donations: 12,
    last_donation_date: '2026-07-20',
    created_at: '2024-11-05',
    verified: true,
  },
  {
    id: 'usr-103',
    name: 'Hamza Sheikh',
    email: 'hamza.sheikh@gmail.com',
    phone: '+92 333 9988776',
    blood_group: 'B+',
    city: 'Karachi',
    is_available: false,
    total_donations: 4,
    last_donation_date: '2026-08-28',
    created_at: '2025-03-14',
    verified: true,
  },
  {
    id: 'usr-104',
    name: 'Zainab Bibi',
    email: 'zainab.b@yahoo.com',
    phone: '+92 345 6677889',
    blood_group: 'AB-',
    city: 'Islamabad',
    is_available: true,
    total_donations: 3,
    last_donation_date: '2026-05-10',
    created_at: '2025-05-20',
    verified: false,
  },
  {
    id: 'usr-105',
    name: 'Usman Ghani',
    email: 'usman.ghani@outlook.com',
    phone: '+92 312 3344556',
    blood_group: 'O+',
    city: 'Rawalpindi',
    is_available: true,
    total_donations: 9,
    last_donation_date: '2026-04-12',
    created_at: '2024-09-18',
    verified: true,
  },
  {
    id: 'usr-106',
    name: 'Mariam Tariq',
    email: 'mariam.tariq@gmail.com',
    phone: '+92 302 7788112',
    blood_group: 'A-',
    city: 'Multan',
    is_available: true,
    total_donations: 5,
    last_donation_date: '2026-07-02',
    created_at: '2025-02-28',
    verified: true,
  }
];

export const mockDonations: DonationRecord[] = [
  {
    id: 'don-801',
    donor_id: 'usr-101',
    donor_name: 'Ali Hassan',
    blood_group: 'O-',
    patient_name: 'Zubair Ahmed',
    hospital: 'Services Hospital',
    city: 'Lahore',
    units: 1,
    donated_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    status: 'VERIFIED',
  },
  {
    id: 'don-802',
    donor_id: 'usr-102',
    donor_name: 'Dr. Sarah Farooq',
    blood_group: 'A+',
    patient_name: 'Fatima Noor',
    hospital: 'Shaukat Khanum Memorial Hospital',
    city: 'Lahore',
    units: 2,
    donated_at: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    status: 'COMPLETED',
  },
  {
    id: 'don-803',
    donor_id: 'usr-103',
    donor_name: 'Hamza Sheikh',
    blood_group: 'B+',
    patient_name: 'Bilal Khan',
    hospital: 'Aga Khan University Hospital',
    city: 'Karachi',
    units: 2,
    donated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    status: 'VERIFIED',
  },
  {
    id: 'don-804',
    donor_id: 'usr-105',
    donor_name: 'Usman Ghani',
    blood_group: 'O+',
    patient_name: 'Hamza Ali',
    hospital: 'Nishtar Hospital',
    city: 'Multan',
    units: 2,
    donated_at: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    status: 'COMPLETED',
  }
];

export const mockMonthlyTrends = [
  { month: 'Jan', requests: 45, fulfilled: 42, newDonors: 60 },
  { month: 'Feb', requests: 52, fulfilled: 48, newDonors: 75 },
  { month: 'Mar', requests: 68, fulfilled: 61, newDonors: 95 },
  { month: 'Apr', requests: 80, fulfilled: 74, newDonors: 110 },
  { month: 'May', requests: 95, fulfilled: 88, newDonors: 130 },
  { month: 'Jun', requests: 110, fulfilled: 102, newDonors: 145 },
  { month: 'Jul', requests: 125, fulfilled: 118, newDonors: 160 },
  { month: 'Aug', requests: 140, fulfilled: 132, newDonors: 185 },
];

export const mockBloodInventoryData = [
  { group: 'A+', count: 245, demand: 85, color: '#f43f5e' },
  { group: 'A-', count: 68, demand: 42, color: '#e11d48' },
  { group: 'B+', count: 310, demand: 110, color: '#be123c' },
  { group: 'B-', count: 54, demand: 38, color: '#9f1239' },
  { group: 'AB+', count: 120, demand: 28, color: '#fb7185' },
  { group: 'AB-', count: 32, demand: 30, color: '#fda4af' },
  { group: 'O+', count: 410, demand: 190, color: '#e11d48' },
  { group: 'O-', count: 48, demand: 95, color: '#ff1a40' },
];
