"use client";

import React from "react";
import { getCityNameById, resolveRequestStatus } from "@/lib/cityUtils";

interface PrintReportViewProps {
  kpis: {
    totalRequests: number;
    totalDonations: number;
    totalFulfilled: number;
    totalCritical: number;
    fulfillmentRate: number;
  };
  cities: any[];
  requests: any[];
  users: any[];
  donations: any[];
  previewMode?: boolean;
  onClosePreview?: () => void;
}

export const PrintReportView: React.FC<PrintReportViewProps> = ({
  kpis,
  cities,
  requests,
  users,
  donations,
  previewMode = false,
  onClosePreview,
}) => {
  const now = new Date();
  const dateFormatted = now.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeFormatted = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
  const reportSerial = `LL-AUDIT-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}-${Math.floor(1000 + Math.random() * 9000)}`;

  const printableContent = (
    <div className="bg-white text-slate-900 font-sans p-8 max-w-5xl mx-auto printable-document">
      {/* ─── OFFICIAL HEADER / LETTERHEAD ─── */}
      <div className="border-b-2 border-slate-900 pb-6 mb-6">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3.5">
            <div className="w-12 h-12 rounded-xl bg-[#e53935] flex items-center justify-center text-white font-black text-2xl tracking-tighter shadow-xs">
              +
            </div>
            <div>
              <h1 className="text-xl font-black tracking-tight uppercase text-slate-950">
                LifeLink National Blood Network
              </h1>
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mt-0.5">
                Central Health Informatics & Administrative Audit Authority
              </p>
              <p className="text-[11px] text-slate-400 font-medium">
                Emergency Transfusion Registry • Official Clinical Command Center
              </p>
            </div>
          </div>

          <div className="text-right">
            <div className="inline-block px-3 py-1 rounded border border-red-200 bg-red-50 text-red-700 text-[11px] font-black tracking-wider uppercase mb-1">
              Official Audit Report
            </div>
            <div className="text-xs font-mono font-bold text-slate-700">REF: {reportSerial}</div>
            <div className="text-[11px] text-slate-500">{dateFormatted}</div>
            <div className="text-[10px] text-slate-400 font-mono">{timeFormatted} PKT</div>
          </div>
        </div>

        <div className="mt-4 pt-3 border-t border-slate-200 flex items-center justify-between text-[11px] text-slate-600">
          <div>
            <span className="font-bold text-slate-800">Classification:</span> Confidential Health Informatics • Administrative Use Only
          </div>
          <div>
            <span className="font-bold text-slate-800">Generated By:</span> Operations Command Center
          </div>
        </div>
      </div>

      {/* ─── EXECUTIVE PLATFORM KPIS ─── */}
      <div className="mb-8">
        <h2 className="text-xs font-black text-slate-900 uppercase tracking-wider mb-3 flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-[#e53935]" />
          Executive Key Performance Indicators
        </h2>

        <div className="grid grid-cols-5 gap-3">
          <div className="border border-slate-300 rounded-lg p-3 bg-slate-50/50">
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Total Blood Requests</div>
            <div className="text-2xl font-black text-slate-900 mt-1">{requests.length || kpis.totalRequests}</div>
            <div className="text-[10px] text-slate-500 mt-0.5">All registered cases</div>
          </div>

          <div className="border border-slate-300 rounded-lg p-3 bg-slate-50/50">
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Registered Donors</div>
            <div className="text-2xl font-black text-slate-900 mt-1">{users.length}</div>
            <div className="text-[10px] text-slate-500 mt-0.5">Verified profiles</div>
          </div>

          <div className="border border-slate-300 rounded-lg p-3 bg-slate-50/50">
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Verified Donations</div>
            <div className="text-2xl font-black text-slate-900 mt-1">{donations.length || kpis.totalDonations}</div>
            <div className="text-[10px] text-slate-500 mt-0.5">Audit log records</div>
          </div>

          <div className="border border-slate-300 rounded-lg p-3 bg-slate-50/50">
            <div className="text-[10px] font-bold text-red-600 uppercase tracking-wider">Critical Cases</div>
            <div className="text-2xl font-black text-red-600 mt-1">{kpis.totalCritical}</div>
            <div className="text-[10px] text-red-500 mt-0.5">Emergency priority</div>
          </div>

          <div className="border border-slate-300 rounded-lg p-3 bg-slate-50/50">
            <div className="text-[10px] font-bold text-emerald-700 uppercase tracking-wider">Fulfillment Rate</div>
            <div className="text-2xl font-black text-emerald-700 mt-1">{kpis.fulfillmentRate}%</div>
            <div className="text-[10px] text-emerald-600 mt-0.5">Transfusion ratio</div>
          </div>
        </div>
      </div>

      {/* ─── SECTION 1: REGIONAL DEMAND & CITY DISTRIBUTION ─── */}
      <div className="mb-8 page-break-inside-avoid">
        <h2 className="text-xs font-black text-slate-900 uppercase tracking-wider mb-3 flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-slate-700" />
          1. Regional Supply & Demand Distribution
        </h2>

        <table className="w-full text-left border-collapse border border-slate-300 text-xs">
          <thead>
            <tr className="bg-slate-100 text-slate-800 font-bold border-b border-slate-300">
              <th className="py-2 px-3 border-r border-slate-300">City / District</th>
              <th className="py-2 px-3 border-r border-slate-300 text-right">Blood Requests</th>
              <th className="py-2 px-3 border-r border-slate-300 text-right">Registered Donors</th>
              <th className="py-2 px-3 border-r border-slate-300 text-right">Fulfilled Cases</th>
              <th className="py-2 px-3 border-r border-slate-300 text-right">Fulfillment Rate</th>
              <th className="py-2 px-3">Operational Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {cities.slice(0, 10).map((c, i) => {
              const rate = c.requests > 0 ? Math.round((c.fulfilled / c.requests) * 100) : 100;
              let badgeClass = "text-emerald-700 font-bold";
              let badgeText = "Balanced Supply";
              if (c.requests > 5 && rate < 30) {
                badgeClass = "text-red-700 font-bold";
                badgeText = "Deficit Alert";
              } else if (c.requests > 2 && rate < 50) {
                badgeClass = "text-amber-700 font-bold";
                badgeText = "Moderate Demand";
              }

              return (
                <tr key={i} className={i % 2 === 1 ? "bg-slate-50/70" : "bg-white"}>
                  <td className="py-1.5 px-3 border-r border-slate-200 font-bold text-slate-900">{c.city}</td>
                  <td className="py-1.5 px-3 border-r border-slate-200 text-right font-mono">{c.requests}</td>
                  <td className="py-1.5 px-3 border-r border-slate-200 text-right font-mono">{c.donors}</td>
                  <td className="py-1.5 px-3 border-r border-slate-200 text-right font-mono">{c.fulfilled}</td>
                  <td className="py-1.5 px-3 border-r border-slate-200 text-right font-mono font-bold">{rate}%</td>
                  <td className={`py-1.5 px-3 ${badgeClass}`}>{badgeText}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ─── SECTION 2: CLINICAL BLOOD REQUESTS ─── */}
      <div className="mb-8 page-break-inside-avoid">
        <h2 className="text-xs font-black text-slate-900 uppercase tracking-wider mb-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#e53935]" />
            2. Clinical Emergency Requests Registry (Active & Recent)
          </div>
          <span className="text-[10px] text-slate-500 font-normal">
            Displaying {Math.min(requests.length, 15)} of {requests.length} records
          </span>
        </h2>

        <table className="w-full text-left border-collapse border border-slate-300 text-[11px]">
          <thead>
            <tr className="bg-slate-100 text-slate-800 font-bold border-b border-slate-300">
              <th className="py-2 px-2.5 border-r border-slate-300">Patient</th>
              <th className="py-2 px-2 border-r border-slate-300 text-center">Group</th>
              <th className="py-2 px-2 border-r border-slate-300 text-center">Units</th>
              <th className="py-2 px-2.5 border-r border-slate-300">Urgency</th>
              <th className="py-2 px-2.5 border-r border-slate-300">Hospital / Facility</th>
              <th className="py-2 px-2.5 border-r border-slate-300">City</th>
              <th className="py-2 px-2.5 border-r border-slate-300">Required Date</th>
              <th className="py-2 px-2.5">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {requests.slice(0, 15).map((r, i) => {
              const rawCity = r.city_id || r.city || r.city_name;
              const cityName = getCityNameById(rawCity);
              const status = resolveRequestStatus(r);
              const reqDate = r.required_date
                ? new Date(r.required_date).toLocaleDateString("en-US", { month: "short", day: "numeric" })
                : "Immediate";

              return (
                <tr key={r.id || i} className={i % 2 === 1 ? "bg-slate-50/70" : "bg-white"}>
                  <td className="py-1.5 px-2.5 border-r border-slate-200 font-bold text-slate-900">
                    {r.patient_name || r.patientName || "Emergency Patient"}
                  </td>
                  <td className="py-1.5 px-2 border-r border-slate-200 text-center font-bold text-red-600">
                    {r.blood_group || r.bloodGroup || "—"}
                  </td>
                  <td className="py-1.5 px-2 border-r border-slate-200 text-center font-mono">
                    {r.units_needed || r.units || 1}
                  </td>
                  <td className="py-1.5 px-2.5 border-r border-slate-200 font-semibold uppercase text-[10px]">
                    <span className={r.urgency === "critical" ? "text-red-600 font-black" : "text-slate-700"}>
                      {r.urgency || "Normal"}
                    </span>
                  </td>
                  <td className="py-1.5 px-2.5 border-r border-slate-200 text-slate-700 truncate max-w-[140px]">
                    {r.hospital_name || r.hospitalName || "Regional Hospital"}
                  </td>
                  <td className="py-1.5 px-2.5 border-r border-slate-200 text-slate-700">{cityName}</td>
                  <td className="py-1.5 px-2.5 border-r border-slate-200 text-slate-600 font-mono text-[10px]">{reqDate}</td>
                  <td className="py-1.5 px-2.5 font-bold uppercase text-[10px]">
                    <span
                      className={
                        status === "open"
                          ? "text-emerald-700"
                          : status === "expired"
                          ? "text-amber-700"
                          : "text-slate-600"
                      }
                    >
                      {status}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ─── SECTION 3: REGISTERED DONORS & VOLUNTEERS ─── */}
      <div className="mb-8 page-break-inside-avoid">
        <h2 className="text-xs font-black text-slate-900 uppercase tracking-wider mb-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-blue-600" />
            3. Registered Donors & Clinical Volunteers Directory
          </div>
          <span className="text-[10px] text-slate-500 font-normal">
            Displaying {Math.min(users.length, 12)} of {users.length} donors
          </span>
        </h2>

        <table className="w-full text-left border-collapse border border-slate-300 text-[11px]">
          <thead>
            <tr className="bg-slate-100 text-slate-800 font-bold border-b border-slate-300">
              <th className="py-2 px-3 border-r border-slate-300">Donor Name</th>
              <th className="py-2 px-2 border-r border-slate-300 text-center">Blood</th>
              <th className="py-2 px-3 border-r border-slate-300">City / District</th>
              <th className="py-2 px-3 border-r border-slate-300">Contact Number</th>
              <th className="py-2 px-3 border-r border-slate-300">Availability</th>
              <th className="py-2 px-3 text-right">Donations</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {users.slice(0, 12).map((u, i) => {
              const rawCity = u.city_id || u.city || u.city_name;
              const cityName = getCityNameById(rawCity);
              const isAvail = u.is_available !== false;

              return (
                <tr key={u.id || i} className={i % 2 === 1 ? "bg-slate-50/70" : "bg-white"}>
                  <td className="py-1.5 px-3 border-r border-slate-200 font-bold text-slate-900">
                    {u.full_name || "Anonymous Donor"}
                  </td>
                  <td className="py-1.5 px-2 border-r border-slate-200 text-center font-bold text-red-600">
                    {u.blood_group || "—"}
                  </td>
                  <td className="py-1.5 px-3 border-r border-slate-200 text-slate-700">{cityName}</td>
                  <td className="py-1.5 px-3 border-r border-slate-200 text-slate-600 font-mono text-[10px]">
                    {u.phone || "—"}
                  </td>
                  <td className="py-1.5 px-3 border-r border-slate-200 font-semibold text-[10px]">
                    <span className={isAvail ? "text-emerald-700 font-bold" : "text-amber-700"}>
                      {isAvail ? "● Available" : "○ Resting"}
                    </span>
                  </td>
                  <td className="py-1.5 px-3 text-right font-mono font-bold text-slate-800">
                    {u.total_donations || 0}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ─── OFFICIAL ATTESTATION & SIGNATURE BLOCK ─── */}
      <div className="pt-6 border-t-2 border-slate-800 page-break-inside-avoid mt-8">
        <div className="grid grid-cols-3 gap-6 text-xs">
          <div>
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-8">
              Medical Officer Authorization
            </div>
            <div className="border-b border-slate-400 pb-1 font-semibold text-slate-800">
              Dr. Asad Mahmood, MD
            </div>
            <div className="text-[10px] text-slate-500 mt-0.5">Director of Clinical Hematology</div>
          </div>

          <div>
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-8">
              Systems Administrator
            </div>
            <div className="border-b border-slate-400 pb-1 font-semibold text-slate-800">
              Lead Operations Officer
            </div>
            <div className="text-[10px] text-slate-500 mt-0.5">LifeLink Command Center</div>
          </div>

          <div className="border border-slate-300 rounded-lg p-3 bg-slate-50 flex flex-col justify-between">
            <div className="text-[10px] font-bold text-slate-700 uppercase tracking-wider text-center">
              Official Seal & Validation
            </div>
            <div className="my-2 border-2 border-dashed border-slate-300 rounded py-2 text-center text-[10px] text-slate-400 font-mono">
              [ OFFICIAL DIGITAL STAMP ]<br />
              SHA-256: {reportSerial.slice(-8)}...
            </div>
            <div className="text-[9px] text-slate-400 text-center">
              Verified by National Transfusion Authority
            </div>
          </div>
        </div>

        <div className="mt-6 pt-3 border-t border-slate-200 text-[10px] text-slate-400 flex items-center justify-between">
          <span>LifeLink Healthcare Informatics • Confidential Patient Data</span>
          <span>Page 1 of 1 • System Generated Report</span>
        </div>
      </div>
    </div>
  );

  if (previewMode) {
    return (
      <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/75 backdrop-blur-xs flex items-center justify-center p-4">
        <div className="bg-slate-100 rounded-2xl w-full max-w-5xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden border border-slate-200">
          {/* Preview Modal Header */}
          <div className="bg-slate-900 text-white px-6 py-4 flex items-center justify-between shrink-0">
            <div>
              <h3 className="text-sm font-bold flex items-center gap-2">
                <span>🖨️ Official Executive Print / PDF Preview</span>
              </h3>
              <p className="text-xs text-slate-400 mt-0.5">
                Formatted for standard A4 / Letter paper with official letterhead and audit tables
              </p>
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={() => window.print()}
                className="px-4 py-2 rounded-xl bg-[#e53935] hover:bg-red-700 text-white text-xs font-bold transition-colors shadow-sm flex items-center gap-1.5"
              >
                <span>Print / Save as PDF</span>
              </button>
              {onClosePreview && (
                <button
                  onClick={onClosePreview}
                  className="px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-bold transition-colors"
                >
                  Close
                </button>
              )}
            </div>
          </div>

          {/* Document Body */}
          <div className="flex-1 overflow-y-auto p-6 bg-slate-200/60">
            <div className="shadow-lg rounded-xl overflow-hidden">{printableContent}</div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div id="printable-report" className="hidden print:block">
      {printableContent}
    </div>
  );
};
